name: Draw keymaps
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
  push:
    paths:
      - "config/*.keymap"
      - "keymap-drawer.config.yaml"
      - ".github/workflows/draw-keymaps.yml"
  workflow_dispatch:

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap-drawer.config.yaml"
      output_folder: "keymap-drawer"
      parse_args: ""
      draw_args: ""
      commit_message: "[keymap-drawer] Update keymap images"