name: Draw keymaps
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
  push:
    paths:
      - "config/*.keymap"
      - "keymap-drawer.config.yaml"
      - ".github/workflows/draw-keymaps.yml"
  workflow_dispatch:

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install keymap-drawer with compatible tree-sitter
        run: |
          pip install "tree-sitter<0.21" "tree-sitter-devicetree<0.21"
          pip install keymap-drawer

      - name: Create output directory
        run: mkdir -p keymap-drawer

      - name: Parse keymap
        run: python -m keymap_drawer parse -z config/corne.keymap > keymap-drawer/corne.yaml

      - name: Draw complete keymap
        run: python -m keymap_drawer draw -z corne keymap-drawer/corne.yaml -o keymap-drawer/corne.svg

      - name: Draw layer 0
        run: python -m keymap_drawer draw -z corne keymap-drawer/corne.yaml --select-layers "default_layer" -o keymap-drawer/corne_layer0.svg

      - name: Draw layer 1
        run: python -m keymap_drawer draw -z corne keymap-drawer/corne.yaml --select-layers "lower_layer" -o keymap-drawer/corne_layer1.svg

      - name: Draw layer 2
        run: python -m keymap_drawer draw -z corne keymap-drawer/corne.yaml --select-layers "raise_layer" -o keymap-drawer/corne_layer2.svg

      - name: Draw layer 3
        run: python -m keymap_drawer draw -z corne keymap-drawer/corne.yaml --select-layers "adjust_layer" -o keymap-drawer/corne_layer3.svg

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add keymap-drawer/
          git diff --staged --quiet || git commit -m "[keymap-drawer] Update keymap images"
          git push